//Source code generated by AppGPT (www.appgpt.tech)

//Class to create tables and seed new database
import { DataSource } from 'typeorm';
import { DBConfiguration } from './Configuration';
import { SettingsEntity } from './db/Settings.entity';
//autogenerate imports based on resources
import { usersEntity } from './db/users.entity';
import { departmentsEntity } from './db/departments.entity';
import { initiativesEntity } from './db/initiatives.entity';
import { goalsEntity } from './db/goals.entity';
import { emissionSourcesEntity } from './db/emissionSources.entity';
import { resourceUsageEntity } from './db/resourceUsage.entity';

export class Database {
  static dbConfiguration: DBConfiguration;
  public static ds: DataSource;

  static async Initialize(dbConfiguration: DBConfiguration) {
    Database.dbConfiguration = dbConfiguration;
    let dbConfig: any = dbConfiguration as any;
    //Autogenerate entities array from resource names

    dbConfig.entities = [
      SettingsEntity,
      usersEntity,
      departmentsEntity,
      initiativesEntity,
      goalsEntity,
      emissionSourcesEntity,
      resourceUsageEntity,
    ];
    Database.ds = new DataSource(dbConfig);
    await Database.ds.initialize();

    //TODO: Drop all tables

    await Database.Seed();
  }
  static async Seed() {
    let data: any = {
      users: [
        {
          userName: 'userName 1',
          department: 1,
          password: 'password 1',
          email: 'email 1',
          id: 21,
        },
        {
          userName: 'userName 2',
          department: 2,
          password: 'password 2',
          email: 'email 2',
          id: 40,
        },
        {
          userName: 'userName 3',
          department: 3,
          password: 'password 3',
          email: 'email 3',
          id: 46,
        },
        {
          userName: 'userName 4',
          department: 4,
          password: 'password 4',
          email: 'email 4',
          id: 33,
        },
        {
          userName: 'userName 5',
          department: 5,
          password: 'password 5',
          email: 'email 5',
          id: 9,
        },
      ],
      departments: [
        { departmentName: 'departmentName 1', departmentHead: 1, id: 0 },
        { departmentName: 'departmentName 2', departmentHead: 2, id: 51 },
        { departmentName: 'departmentName 3', departmentHead: 3, id: 5 },
        { departmentName: 'departmentName 4', departmentHead: 4, id: 65 },
        { departmentName: 'departmentName 5', departmentHead: 5, id: 54 },
      ],
      initiatives: [
        {
          name: 'name 1',
          description: 'description 1',
          startDate: '2024-05-08T07:38:45.349Z',
          endDate: '2023-11-27T02:00:23.199Z',
          relatedDepartment: 1,
          status: 'status 1',
          id: 93,
        },
        {
          name: 'name 2',
          description: 'description 2',
          startDate: '2023-11-08T03:41:40.333Z',
          endDate: '2023-09-29T08:08:37.420Z',
          relatedDepartment: 2,
          status: 'status 2',
          id: 3,
        },
        {
          name: 'name 3',
          description: 'description 3',
          startDate: '2024-11-12T10:50:16.970Z',
          endDate: '2024-08-29T02:24:15.629Z',
          relatedDepartment: 3,
          status: 'status 3',
          id: 39,
        },
        {
          name: 'name 4',
          description: 'description 4',
          startDate: '2025-03-20T07:49:44.260Z',
          endDate: '2023-08-05T05:21:58.286Z',
          relatedDepartment: 4,
          status: 'status 4',
          id: 71,
        },
        {
          name: 'name 5',
          description: 'description 5',
          startDate: '2025-04-01T19:06:25.255Z',
          endDate: '2023-06-10T10:27:54.820Z',
          relatedDepartment: 5,
          status: 'status 5',
          id: 75,
        },
      ],
      goals: [
        {
          name: 'name 1',
          description: 'description 1',
          targetDate: '2024-09-13T20:00:07.484Z',
          relatedDepartment: 1,
          status: 'status 1',
          id: 5,
        },
        {
          name: 'name 2',
          description: 'description 2',
          targetDate: '2025-01-22T12:56:44.569Z',
          relatedDepartment: 2,
          status: 'status 2',
          id: 76,
        },
        {
          name: 'name 3',
          description: 'description 3',
          targetDate: '2025-03-24T09:19:50.778Z',
          relatedDepartment: 3,
          status: 'status 3',
          id: 91,
        },
        {
          name: 'name 4',
          description: 'description 4',
          targetDate: '2023-08-16T22:32:50.666Z',
          relatedDepartment: 4,
          status: 'status 4',
          id: 4,
        },
        {
          name: 'name 5',
          description: 'description 5',
          targetDate: '2025-02-12T10:15:59.300Z',
          relatedDepartment: 5,
          status: 'status 5',
          id: 85,
        },
      ],
      emissionSources: [
        {
          sourceType: 'sourceType 1',
          quantityUsed: 0.67,
          emissionFactors: 0.22,
          totalEmissions: 0.05,
          id: 85,
        },
        {
          sourceType: 'sourceType 2',
          quantityUsed: 0.86,
          emissionFactors: 0.21,
          totalEmissions: 0.19,
          id: 35,
        },
        {
          sourceType: 'sourceType 3',
          quantityUsed: 0.17,
          emissionFactors: 0.5,
          totalEmissions: 0.04,
          id: 28,
        },
        {
          sourceType: 'sourceType 4',
          quantityUsed: 0.22,
          emissionFactors: 0.82,
          totalEmissions: 0.76,
          id: 39,
        },
        {
          sourceType: 'sourceType 5',
          quantityUsed: 0.02,
          emissionFactors: 0.93,
          totalEmissions: 0.1,
          id: 56,
        },
      ],
      resourceUsage: [
        {
          resourceType: 'resourceType 1',
          quantityConsumed: 0.35,
          unitOfMeasurement: 'unitOfMeasurement 1',
          periodOfConsumption: '2024-06-16T15:31:06.731Z',
          id: 93,
        },
        {
          resourceType: 'resourceType 2',
          quantityConsumed: 0.04,
          unitOfMeasurement: 'unitOfMeasurement 2',
          periodOfConsumption: '2025-01-20T17:22:35.484Z',
          id: 42,
        },
        {
          resourceType: 'resourceType 3',
          quantityConsumed: 0.52,
          unitOfMeasurement: 'unitOfMeasurement 3',
          periodOfConsumption: '2023-11-23T06:32:27.112Z',
          id: 39,
        },
        {
          resourceType: 'resourceType 4',
          quantityConsumed: 0.79,
          unitOfMeasurement: 'unitOfMeasurement 4',
          periodOfConsumption: '2025-02-28T17:00:06.513Z',
          id: 81,
        },
        {
          resourceType: 'resourceType 5',
          quantityConsumed: 0.92,
          unitOfMeasurement: 'unitOfMeasurement 5',
          periodOfConsumption: '2024-12-23T17:59:07.567Z',
          id: 92,
        },
      ],
    };
    //Autogenerate multiple such calls ie for each resource and its data object
    let isSeeded = await this.IsSeeded();
    //if (!isSeeded) {
    //forcing app recreation
    if (true) {
      console.log('   Seeding database...');
      await this.SeedResource('usersEntity', data.users);
      await this.SeedResource('departmentsEntity', data.departments);
      await this.SeedResource('initiativesEntity', data.initiatives);
      await this.SeedResource('goalsEntity', data.goals);
      await this.SeedResource('emissionSourcesEntity', data.emissionSources);
      await this.SeedResource('resourceUsageEntity', data.resourceUsage);
      await this.SeedResource('SettingsEntity', {
        settingname: 'isSeeded',
        settingvalue: 'true',
      });
    } else {
      console.log('   Database seeded already!');
    }
  }
  static async IsSeeded() {
    const repo = Database.ds.getRepository('SettingsEntity');
    let rec: any = await repo.findOne({
      select: {
        settingname: true,
        settingvalue: true,
      },
      where: {
        settingname: 'isSeeded',
      },
    });
    if (rec && rec.settingvalue) return true;
    return false;
  }
  static async SeedResource(resourceName: any, resourceData: any) {
    const repo = Database.ds.getRepository(resourceName);
    //await repo.clear();
    console.log('   Seeding table ' + resourceName);
    await repo.upsert(resourceData, ['id']);
  }
}
